### ISSUE TITLE
Hex package

### ISSUE THREAD

**Issue by tsloughter** [kivra/oauth2_client#14]
Would be great to make this and restclient hex packages :)

**Comment by tsloughter** [comment]
I should mention I'm working on Swagger support for Erlang clients and want to point to an Erlang oauth2 client for it to work well with.

**Comment by plux** [comment]
Thanks for the feedback, we'll look into creating hex packages.

**Comment by plux** [comment]
I've published the package to hex.pm now: https://hex.pm/packages/oauth2c

restclient is already on hex, you may find it here: https://hex.pm/packages/restc

We should probably look into if it's possible to move restc to the kivra organization on hex.pm
